services:
  postgres:
    image: postgres:16
    container_name: bookshop-postgres
    environment:
      POSTGRES_DB: bookshop
      POSTGRES_USER: bookshop_user
      POSTGRES_PASSWORD: bookshop_pass
    ports:
      - "5432:5432"
    volumes:
      - bookshop_pgdata:/var/lib/postgresql/data

volumes:
  bookshop_pgdata:
